"""
Service: Data Cleaning Pipeline Orchestrator (Stateful History, Audit Trail, Code Exporter)
"""
import time
from datetime import datetime
from typing import List, Tuple, Optional, Dict, Any
import pandas as pd

from cleaner.domain.cleaning_config import (
    DuplicateConfig,
    ImputationConfig,
    OutlierConfig,
    EncodingConfig,
    ScalingConfig
)
from cleaner.domain.cleaning_result import AuditEntry, CleaningResult
from cleaner.domain.validation_rules import ValidationRule, ValidationReport
from cleaner.services.duplicate_remover import DuplicateRemoverService
from cleaner.services.imputer import ImputerService
from cleaner.services.outlier_detector import OutlierDetectorService
from cleaner.services.encoder import EncoderService
from cleaner.services.scaler import ScalerService
from cleaner.services.data_validator import DataValidatorService

class CleaningPipeline:
    """Orchestrator for managing multi-step data cleaning pipelines"""

    def __init__(self, df: pd.DataFrame):
        self.raw_df: pd.DataFrame = df.copy()
        self.current_df: pd.DataFrame = df.copy()
        self.history: List[Tuple[pd.DataFrame, AuditEntry, str]] = [] # (dataframe_snapshot, audit_entry, python_code)
        self.audit_log: List[AuditEntry] = []
        self.code_snippets: List[str] = [
            "# Data Cleaning Script generated by DataViz Pro Platform",
            "import pandas as pd",
            "import numpy as np",
            "from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder",
            "from sklearn.impute import SimpleImputer, KNNImputer",
            "\n# Load dataset",
            "df = pd.read_csv('your_dataset.csv')"
        ]

        # Inject services
        self.duplicate_service = DuplicateRemoverService()
        self.imputer_service = ImputerService()
        self.outlier_service = OutlierDetectorService()
        self.encoder_service = EncoderService()
        self.scaler_service = ScalerService()
        self.validator_service = DataValidatorService()

    def remove_duplicates(self, config: DuplicateConfig) -> CleaningResult:
        start_time = time.time()
        rows_before, cols_before = self.current_df.shape

        cleaned_df, audit = self.duplicate_service.process(self.current_df, config)

        code = f"# Duplicate Removal\nsubset = {config.subset}\ndf = df.drop_duplicates(subset=subset, keep='{config.keep}')"
        self._record_step(cleaned_df, audit, code)

        return CleaningResult(
            df_cleaned=self.current_df,
            rows_before=rows_before,
            rows_after=self.current_df.shape[0],
            cols_before=cols_before,
            cols_after=self.current_df.shape[1],
            duration_seconds=round(time.time() - start_time, 3),
            audit_entries=[audit]
        )

    def impute_missing(self, config: ImputationConfig) -> CleaningResult:
        start_time = time.time()
        rows_before, cols_before = self.current_df.shape

        cleaned_df, audit = self.imputer_service.process(self.current_df, config)

        code = f"# Missing Value Imputation\n# Imputed missing values across columns using {config.default_numeric_strategy}/{config.default_categorical_strategy}"
        self._record_step(cleaned_df, audit, code)

        return CleaningResult(
            df_cleaned=self.current_df,
            rows_before=rows_before,
            rows_after=self.current_df.shape[0],
            cols_before=cols_before,
            cols_after=self.current_df.shape[1],
            duration_seconds=round(time.time() - start_time, 3),
            audit_entries=[audit]
        )

    def handle_outliers(self, config: OutlierConfig) -> CleaningResult:
        start_time = time.time()
        rows_before, cols_before = self.current_df.shape

        cleaned_df, audit = self.outlier_service.process(self.current_df, config)

        code = f"# Outlier Detection ({config.method.upper()})\n# Action: {config.action}"
        self._record_step(cleaned_df, audit, code)

        return CleaningResult(
            df_cleaned=self.current_df,
            rows_before=rows_before,
            rows_after=self.current_df.shape[0],
            cols_before=cols_before,
            cols_after=self.current_df.shape[1],
            duration_seconds=round(time.time() - start_time, 3),
            audit_entries=[audit]
        )

    def encode_categories(self, config: EncodingConfig) -> CleaningResult:
        start_time = time.time()
        rows_before, cols_before = self.current_df.shape

        cleaned_df, audit = self.encoder_service.process(self.current_df, config)

        code = f"# Categorical Encoding ({config.strategy})\ndf = pd.get_dummies(df, drop_first={config.drop_first})" if config.strategy == 'onehot' else f"# Categorical Encoding ({config.strategy})"
        self._record_step(cleaned_df, audit, code)

        return CleaningResult(
            df_cleaned=self.current_df,
            rows_before=rows_before,
            rows_after=self.current_df.shape[0],
            cols_before=cols_before,
            cols_after=self.current_df.shape[1],
            duration_seconds=round(time.time() - start_time, 3),
            audit_entries=[audit]
        )

    def scale_features(self, config: ScalingConfig) -> CleaningResult:
        start_time = time.time()
        rows_before, cols_before = self.current_df.shape

        cleaned_df, audit = self.scaler_service.process(self.current_df, config)

        code = f"# Feature Scaling ({config.strategy.title()} Scaler)"
        self._record_step(cleaned_df, audit, code)

        return CleaningResult(
            df_cleaned=self.current_df,
            rows_before=rows_before,
            rows_after=self.current_df.shape[0],
            cols_before=cols_before,
            cols_after=self.current_df.shape[1],
            duration_seconds=round(time.time() - start_time, 3),
            audit_entries=[audit]
        )

    def validate_data(self, rules: List[ValidationRule]) -> ValidationReport:
        return self.validator_service.validate(self.current_df, rules)

    def undo_last_step(self) -> Optional[AuditEntry]:
        if not self.history:
            return None
        self.history.pop()
        self.audit_log.pop()
        self.code_snippets.pop()

        if self.history:
            self.current_df = self.history[-1][0].copy()
        else:
            self.current_df = self.raw_df.copy()
        return True

    def reset_to_raw(self) -> None:
        self.current_df = self.raw_df.copy()
        self.history.clear()
        self.audit_log.clear()
        self.code_snippets = self.code_snippets[:7]

    def generate_python_code(self) -> str:
        return "\n\n".join(self.code_snippets)

    def _record_step(self, df_new: pd.DataFrame, audit: AuditEntry, python_code: str):
        self.current_df = df_new
        self.history.append((df_new.copy(), audit, python_code))
        self.audit_log.append(audit)
        self.code_snippets.append(python_code)
